export { default as Event } from 'events_/Event'
export { default as ErrorEvent } from 'events_/ErrorEvent'
export { default as ProgressEvent } from 'events_/ProgressEvent'
export { default as ResourceEvent } from 'events_/ResourceEvent'
export { default as OrientationEvent } from 'events_/OrientationEvent'