export {default as DeviceManager} from 'managers/DeviceManager'
export {default as DisplayManager} from 'managers/DisplayManager'
export {default as EventsManager} from 'managers/EventsManager'
export {default as TimeManager} from 'managers/TimeManager'
export {default as ScenesManager} from 'managers/ScenesManager'
export {default as CreateManager} from 'managers/CreateManager'
export {default as ResourcesManager} from 'managers/ResourcesManager'