export {default as DeviceManager} from 'core/managers/DeviceManager'
export {default as TimeManager} from 'core/managers/TimeManager'
export {default as DisplayManager} from 'core/managers/DisplayManager'
export {default as DirectorManager} from 'core/managers/DirectorManager'
export {default as EventsManager} from 'core/managers/EventsManager'
export {default as KeyboardManager} from 'core/managers/KeyboardManager'