// export {default as AnimatedSprite} from 'sk/displayObjects/AnimatedSprite.js'
export {default as Sprite} from 'sk/displayObjects/Sprite.js'
export {default as Text} from 'sk/displayObjects/Text.js'
export {default as BitmapText} from 'sk/displayObjects/BitmapText.js'
export {default as Graphics} from 'sk/displayObjects/Graphics.js'