module.exports = {
  Audio       : require('sk/core/Audio'),
  BaseAudio   : require('sk/core/BaseAudio'),
  Engine      : require('sk/core/Engine'),
  Gamepad     : require('sk/core/Gamepad'),
  Injector    : require('sk/core/Injector'),
  Manager     : require('sk/core/Manager'),
  Middleware  : require('sk/core/Middleware'),
  Resource    : require('sk/core/Resource'),
  Service     : require('sk/core/Service'),
  Signal      : require('sk/core/Signal'),
  SpriteSheet : require('sk/core/SpriteSheet'),
  View        : require('sk/core/View'),
  Touch       : require('sk/core/Touch'),
}
