module.exports = {
  Audio       : require('sk/core/Audio'),
  BaseAudio   : require('sk/core/BaseAudio'),
  Gamepad     : require('sk/core/Gamepad'),
  Manager     : require('sk/core/Manager'),
  Middleware  : require('sk/core/Middleware'),
  Resource    : require('sk/core/Resource'),
  Service     : require('sk/core/Service'),
  Signal      : require('sk/core/Signal'),
  SpriteSheet : require('sk/core/SpriteSheet'),
  Touch       : require('sk/core/Touch'),
  FontStyle   : require('sk/core/FontStyle'),
  Component   : require('sk/core/Component'),
  View        : require('sk/core/View'),
}
