import * as c from 'core/constants'

export default {
  align              : 'left',
  breakWords         : false,
  dropShadow         : false,
  dropShadowAngle    : Math.PI / 6,
  dropShadowBlur     : 0,
  dropShadowColor    : '#000000',
  dropShadowDistance : 5,
  fill               : '#FFFFFF',
  fillGradientType   : c.TEXT_GRADIENT.LINEAR_VERTICAL,
  fontFamily         : 'Arial',
  fontSize           : 26,
  fontStyle          : 'normal',
  fontVariant        : 'normal',
  fontWeight         : 'normal',
  letterSpacing      : 0,
  lineHeight         : 0,
  lineJoin           : 'miter',
  miterLimit         : 10,
  padding            : 0,
  stroke             : 'black',
  strokeThickness    : 0,
  textBaseline       : 'alphabetic',
  wordWrap           : false,
  wordWrapWidth      : 100,
}